import type { Property } from '@/lib/types';

/**
 * @fileOverview Mocks de propiedades sincronizados con la interfaz técnica global.
 */

export const properties: Property[] = [
  {
    id: "1",
    titulo: "Loft Belgrano",
    descripcion: "Espectacular loft moderno en el corazón de Belgrano.",
    precio: 185000,
    imagen: "1",
    imageHint: "modern loft",
    metros: 65,
    supTotal: 65,
    supCubierta: 60,
    ambientes: 2,
    dormitorios: 1,
    banos: "1",
    calle: "Av. Cabildo",
    numero: "1500",
    piso: "4",
    unidad: "A",
    barrio: "Belgrano",
    ciudad: "CABA",
    provincia: "CABA",
    lat: -34.56,
    lng: -58.45,
    operacion: "Venta",
    tipo: "Departamento",
    moneda: "USD",
    cochera: false,
    aptoCredito: true,
    escritura: true,
    pozo: false,
    aEstrenar: false,
    destacado: true,
    userId: "demo-user",
    tenantId: "demo-tenant",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "2",
    titulo: "Depto Palermo",
    descripcion: "Luminoso departamento de 3 ambientes en Palermo Hollywood.",
    precio: 298000,
    imagen: "2",
    imageHint: "suburban house",
    metros: 85,
    supTotal: 85,
    supCubierta: 80,
    ambientes: 3,
    dormitorios: 2,
    banos: "2",
    calle: "Honduras",
    numero: "4800",
    piso: "2",
    unidad: "C",
    barrio: "Palermo",
    ciudad: "CABA",
    provincia: "CABA",
    lat: -34.58,
    lng: -58.42,
    operacion: "Venta",
    tipo: "Departamento",
    moneda: "USD",
    cochera: true,
    aptoCredito: true,
    escritura: true,
    pozo: false,
    aEstrenar: false,
    destacado: true,
    userId: "demo-user",
    tenantId: "demo-tenant",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
